
# multiplicative random effects model:  the rating Y, 0 or 1, is
# generated by
# 
# EY_ij = p + q EU_i EI_j
#
# where EU_i is the mean rating for user i over all possible items and
# similarly EIj for item j

# the EU_i and EI_j are estimated from sample user means, and p and q by
# a simple linear regression, predicting the Y_ij frmo the products of
# the sample user and item mean

# this is a very simple model, whose virtue is simplicity and quick
# computation

# arguments:

#   ratingsIn: input data, with first cols (userID,itemID,rating,
#              covariates); data frame

# value:

#   S3 class of type "MMmultiplic", with components:

#      alphavec: user means
#      betavec: item means 
#      lmcoef: lm() output coefs, used for predicting, the p and q in
#              the above comment

findAlphBet <- function(ratingsIn) {
   users = ratingsIn[,1] 
   items = ratingsIn[,2] 
   ratings = ratingsIn[,3] 
###      linenums <- 1:nrow(ratingsIn)
###      userseqnums <- split(linenums,users)
###      itemseqnums <- split(linenums,items)
###      yidots <- sapply(userseqnums,
###         function(oneuserseqs) mean(ratings[oneuserseqs]))
###      ydotjs <- sapply(itemseqnums,
###         function(oneitemseqs) mean(ratings[oneitemseqs]))
###      alphavec <- yidots 
###      betavec <- ydotjs 
   yd <- findYdotsMM(ratingsIn)
   alphavec <- yd$usrMeans
   betavec <- yd$itmMeans
   pred = 
      alphavec[as.character(users)] * 
      betavec[as.character(items)]
   lmcoef <- coef(lm(ratings ~ pred))
   res <- list(alphavec=alphavec,betavec=betavec,lmcoef=lmcoef)
   class(res) <- 'MMmultiplic'
   res
} 

# predict() method for the 'MMmultiplic' class
#
# testSet in same form as ratingsIn above, except that there 
# is no ratings column 

# MMmultiplic is the output of findAlphBet()
#
# returns vector of predicted values for testSet, i.e. estimated
# probabilities of rating = 1
predict.MMmultiplic = function(multiplicObj,testSet) {
   tmp <- 
      multiplicObj$alphavec[as.character(testSet[,1])] * 
      multiplicObj$betavec[as.character(testSet[,2])] 
   lmc <- multiplicObj$lmcoef
   tmp <- lmc[1] + lmc[2]*tmp
   tmp <- pmin(tmp,1)
   pmax(tmp,0)
}

